/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/3d/ie-97-blue.gltf');
  return (
    <group {...props} dispose={null} scale={6}>
      <mesh
        geometry={nodes.Curve.geometry}
        material={materials['Material.004']}
        position={[0, -0.03, 0]}
        rotation={[1.44, 0.09, -0.64]}
        scale={2.96}
      />
    </group>
  );
}

useGLTF.preload('/3d/ie-97-blue.gltf');
